runtime: python39

handlers:
  - url: /static
    static_dir: static
  
  - url: /
    script: auto

  - url: /result
    script: rest.py
    methods: [POST]

  - url: /stock/.*
    script: rest.py

  - url: /top
    script: rest.py

env_variables:
  ENVIRONMENT: 'production'